services:

  db:
    image: postgres:15

    environment:
      POSTGRES_DB: netflow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U admin -d netflow"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:alpine

    ports:
      - "6379:6379"

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 10


  backend:
    build: .

    ports:
      - "8000:8000"

    environment:
      REDIS_HOST: redis
      DATABASE_URL: postgresql://admin:password@db:5432/netflow

    depends_on:

      redis:
        condition: service_healthy

      db:
        condition: service_healthy

    volumes:
      - .:/app

    restart: unless-stopped


volumes:
  postgres_data: